---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-unreachable-node-cleaner
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-unreachable-node-cleaner
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-unreachable-node-cleaner
roleRef:
  kind: ClusterRole
  name: k8s-unreachable-node-cleaner
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: k8s-unreachable-node-cleaner
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-unreachable-node-cleaner
  namespace: kube-system
  labels:
    app.kubernetes.io/name: k8s-unreachable-node-cleaner
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-unreachable-node-cleaner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-unreachable-node-cleaner
    spec:
      serviceAccountName: k8s-unreachable-node-cleaner
      containers:
        - name: k8s-unreachable-node-cleaner
          image: ghcr.io/matti/k8s-unreachable-node-cleaner:cf09b9b9f3af2daa6dc23dad243a15a6133a638d
          args:
            - "5"
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          env:
            - name: K8S_UNREACHABLE_NODE_CLEANER_DELAY
              value: "10"
